// <auto-generated />
using AppPractise.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppPractise.Migrations
{
    [DbContext(typeof(StudentsDbContext))]
    [Migration("20220818021001_hi")]
    partial class hi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppPractise.Models.Students", b =>
                {
                    b.Property<int>("rollNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rollNo"), 1L, 1);

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("cityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("rollNo");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
